=== MinELenI/CBSviewer/src/main/xsd/AvailableLayers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
	xmlns:l="http://xml.util.cbsviewer.mineleni.nl"
	targetNamespace="http://xml.util.cbsviewer.mineleni.nl" 
	jaxb:version="2.0" attributeFormDefault="qualified"
	elementFormDefault="qualified">

	<xsd:element name="Layers" type="l:layersList">
        <xsd:annotation>
			<xsd:documentation>
				Beschrijft een verzameling van kaartlagen voor de
				applicatie.
			</xsd:documentation>
		</xsd:annotation>
    </xsd:element>

	<xsd:complexType name="layersList">
		<xsd:sequence>
			<xsd:element name="Layerdescriptor" type="l:layerDescriptor" 
				maxOccurs="unbounded" minOccurs="1">
				<xsd:unique name="uniqueLayerDescriptor">
					<xsd:selector xpath="layerDescriptor" />
					<xsd:field xpath="id" />
				</xsd:unique>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="layerDescriptor">
		<xsd:annotation>
			<xsd:documentation>
				Beschrijft een kaartlaag voor de applicatie. Een
				laag kan bestaan uit 1 of meer lagen van 1 WMS.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element type="xsd:ID" name="id" nillable="false" minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>
						De unieke identifier van deze kaartlaag.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element type="xsd:string" name="name" nillable="false" minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>
						De beschrijvende naam van deze kaartlaag.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element type="xsd:string" name="layers" nillable="false" minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>
						Een kommagescheiden string met een of meer namen
						van de LAYERS van de WMS.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element type="xsd:anyURI" name="url" nillable="false" minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>
						De base URL van de WMS waar deze kaartlaag uit
						opgebouwd wordt.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element type="xsd:string" name="styles" nillable="false" minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>
						De lijst met STYLES, een kommagescheiden string
						met een of meer namen van de styles van de WMS.
						Het aantal moet gelijk zijn aan het aantal
						lagen.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element type="xsd:string" name="attributes" nillable="false" minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>
						De te tonen feature attributen als resultaat van
						een FeatureInfo request (kommagescheiden string).
						Dit geeft de mogelijkheid om attributen zoals een
						FeatureId uit de lijst te filteren, deze match is 
						case-sensitive.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="aliases" type="xsd:string" maxOccurs="1" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						De (optionele) alias mapping voor attributes
						(kommagescheiden string). LET OP, het aantal aliases
						dient hetzelfde te zijn als het aantal attributes.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="link" type="xsd:anyURI" maxOccurs="1" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						De (optionele) download link voor de dataset
						waarvan deze (WMS) laag is gemaakt.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== MinELenI/CBSviewer/src/test/resources/invalidAvailableLayers.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Layers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://xml.util.cbsviewer.mineleni.nl" xsi:schemaLocation="http://xml.util.cbsviewer.mineleni.nl AvailableLayers.xsd">
	<!-- dit is een document met een volgens de xsd ongeldige test configuratie, 
		oa. voor AvailableLayersXMLTest -->
	<Layerdescriptor>
		<id>vierkanten500m_oad2000</id>
		<name>Vierkanten 500 x 500m - Omgevingsadressendichtheid 2000</name>
		<layers>omgevings_adres_dichtheid_2000</layers>
		<url>http://geodata.nationaalgeoregister.nl/cbsvierkanten500m/wms</url>
		<styles>cbsvierkanten500m.oad2000</styles>
		<attributes>oad2000</attributes>
	</Layerdescriptor>
	<Layerdescriptor>
		<!-- expres een al gebruikte id waarde -->
		<id>vierkanten500m_oad2000</id>
		<name>Vierkanten 500 x 500m - Omgevingsadressendichtheid 2000</name>
		<layers>omgevings_adres_dichtheid_2000</layers>
		<url>http://geodata.nationaalgeoregister.nl/cbsvierkanten500m/wms</url>
		<styles>cbsvierkanten500m.oad2000</styles>
		<attributes>oad2000</attributes>
	</Layerdescriptor>
</Layers>

=== MinELenI/CBSviewer/src/test/resources/AvailableLayers.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Layers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://xml.util.cbsviewer.mineleni.nl" xsi:schemaLocation="http://xml.util.cbsviewer.mineleni.nl AvailableLayers.xsd">
	<!-- 
		dit is een document met test configuratie, 
		oa. voor AvailableLayersXMLTest en WMSClientServletTest
	-->
	<Layerdescriptor>
		<id>vierkanten500m_oad2000</id>
		<name>Vierkant 500m - Omgevingsadressendichtheid 2000</name>
		<layers>omgevings_adres_dichtheid_2000</layers>
		<url>http://geodata.nationaalgeoregister.nl/cbsvierkanten500m/wms</url>
		<styles>cbsvierkanten500m.oad2000</styles>
		<attributes>oad2000</attributes>
		<aliases>dichtheid</aliases>
	</Layerdescriptor>
	<Layerdescriptor>
		<id>wijkenbuurten2011_thema_gemeenten2011_aantal_inwoners</id>
		<name>CBS Gemeenten 2011 - Aantal inwoners</name>
		<layers>gemeenten2011</layers>
		<url>http://geodata.nationaalgeoregister.nl/wijkenbuurten2011/wms</url>
		<styles>wijkenbuurten2011_thema_gemeenten2011_aantal_inwoners</styles>
		<attributes>aantal_inwoners</attributes>
		<link>http://geodata.nationaalgeoregister.nl/wijkenbuurten2011/wfs?request=GetFeature&amp;typeName=wijkenbuurten2011:gemeenten2011&amp;outputFormat=SHAPE-ZIP</link>
	</Layerdescriptor>
</Layers>
